services:
  db:
    image: postgres:latest
    restart: no
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: docker
      POSTGRES_DB: golang
      POSTGRES_PASSWORD: dockerpwd

volumes:
  db:
    driver: local
